# Generated by Django 4.1.3 on 2022-12-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpareParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255, verbose_name="Nome da Peça"
                    ),  # noqa E501
                ),
                (
                    "number",
                    models.CharField(
                        max_length=255,
                        verbose_name="Número de Identificação da Peça",  # noqa E501
                    ),
                ),
                (
                    "minimum_stock",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Quantidade Miníma de Estoque",
                    ),
                ),
                (
                    "maximum_stock",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Quantidade Maxíma de Estoque",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Quantidade Atual do Estoque",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("feedstock", "Matéria-prima"),
                            ("retail-goods", "Bens para varejo"),
                            (
                                "internal-consumption",
                                "Consumo interno da organização",
                            ),  # noqa E501
                            ("safety-stock", "Estoque de segurança"),
                        ],
                        max_length=32,
                        verbose_name="Tipo do Material",
                    ),
                ),
            ],
            options={
                "verbose_name": "Peça",
                "verbose_name_plural": "Peças",
            },
        ),
    ]
